// Generated by CoffeeScript 1.9.3
(function() {
  var assert, parser;

  parser = require('../libs/yaml.js');

  assert = require('assert');

  describe('Parsing tests', function() {
    return it("should parse a yml and return its results", function(done) {
      parser.getdata('test');
      return done();
    });
  });

}).call(this);
