// Generated by CoffeeScript 1.10.0
(function() {
  var App, YAML, debug, genDockerFile, instances;

  YAML = require('yamljs');

  instances = "instances";

  genDockerFile = require('./libs/docker.js').genDockerFile;

  debug = require('debug')('container:starter');

  App = (function() {
    function App(author, app) {
      this.author = author;
      this.app = author + "/" + app;
      this.tubs = [];
      this.dir = instances + "/" + this.app;
      this.ymlfile = this.dir + "/.jakhu.yml";
      this.parsedYml = YAML.load(this.ymlfile);
    }

    App.prototype.addTub = function(tubname) {
      return this.tubs.push(tubname);
    };

    App.prototype.autoTubs = function() {
      var i, results;
      i = 0;
      results = [];
      while (i < this.parsedYml.tubs.length) {
        genDockerFile(this.parsedYml.tubs[i], this.dir, this.parsedYml);
        results.push(i++);
      }
      return results;
    };

    App.prototype.final = function() {
      return console.log(this.parsedYml);
    };

    App.prototype.createDockerFiles = function() {
      var i, results;
      i = 0;
      results = [];
      while (i < this.tubs.length) {
        genDockerFile(this.tubs[i], this.dir, this.parsedYml);
        results.push(i++);
      }
      return results;
    };

    App.prototype.start = function() {
      return genDockerFile();
    };

    return App;

  })();

  module.exports = {
    App: App
  };

}).call(this);
