#!/usr/bin/bash
echo Preparing to run web-app...
echo Exporting Enviroment...
echo Setting default env...
export CONTAINER_ID=6549685462377966
export CONTAINER_NAME=test
export PORT=8080
export PUBLIC_PORT=3000
echo Setting enviroment varibles from .web.yml...
export WEB_DOCKER=false
export NODE_ENV=dev
echo Updating nodejs...
nvm install stable
echo Installing ruby...
sudo apt-get install ruby-full
echo Installing bundle...
gem install bundle
echo Installing global npm modules...
npm install -g bower grunt-cli 
echo Installing gems...
gem install rails 
cd ./app
echo Building Web-app...
grunt compile
echo Starting Web-app...
export PORT=8080
npm start