#!/usr/bin/bash
echo Preparing to run web-app...
echo Setting enviroment from .web.yml...
export WEB_DOCKER=false
echo Updating nodejs...
nvm install stable
echo Installing ruby...
sudo apt-get install ruby-full
echo Installing bundle...
gem install bundle
echo Installing global npm modules...
npm install -g bower grunt-cli 
echo Installing gems...
gem install rails 
cd ./app
echo Building Web-app...
grunt compile
echo Starting Web-app...
export PORT=8080
npm start