FROM ubuntu:latest
# Update
RUN apt-get update
#Install curl and git
RUN apt-get install -y curl
RUN apt-get install -y git-core
# Install java
RUN apt-get install -y default-jre
RUN apt-get install -y default-jdk
# MVn and ant
RUN apt-get install -y maven
RUN apt-get install -y ant
# Done!
