// Generated by CoffeeScript 1.9.3
(function() {
  var YAML, fs;

  YAML = require('yamljs');

  fs = require('fs');

  module.exports = getdata(ins)(function() {
    return YAML.parse(fs.readFileSync('../../instances/' + ins + '.web.yml', 'utf8'));
  });

}).call(this);
