// Generated by CoffeeScript 1.10.0
(function() {
  var YAML, fs;

  YAML = require('yamljs');

  fs = require('fs');

  module.exports = {
    getdata: function(ins) {
      return YAML.parse(fs.readFileSync('./instances/' + ins + '/.web.yml', 'utf8'));
    }
  };

}).call(this);
