FROM ubuntu:latest
# Update
RUN apt-get update
# Install Curl + Git
RUN apt-get install -y curl git-core
# Install python
RUN apt-get install python
# PIP
curl --silent https://bootstrap.pypa.io/get-pip.py | python -
# Done!
