FROM ubuntu:latest
# Update
RUN apt-get update
# Install Curl + Git
RUN apt-get install -y curl
RUN apt-get install -y git-core
# Install python
RUN apt-get install -y python
# PIP
RUN curl --silent https://bootstrap.pypa.io/get-pip.py | python -
# Done!
