#!/usr/bin/bash
# Runs on docker to build + run nodejs
echo Preparing to run Web-app...
./nvm.sh
echo Installing global dependencies...
# Bower, grunt, coffee-script
./global.sh
echo Installing dependencies...
./install.sh
# Could be cake for coffe or node-gyp
echo Building...
./build.sh
echo
echo Running Web-app...
./startx.sh
